name: SwissArmyKnife.Avalonia

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:      
      - name: set TAG
        if: ${{ matrix.os == 'windows-latest' }} 
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $env:GITHUB_ENV
      - name: set TAG
        if: ${{ matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' }} 
        run: echo "TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: SwissArmyKnife
      - uses: actions/checkout@v2
        with:
          repository: PlatinumMaster/BeaterLibrary
          path: BeaterLibrary
      - uses: actions/checkout@v2
        with:
          repository: PlatinumMaster/Hotswap
          path: Hotswap
      - uses: actions/checkout@v2
        with:
          repository: PlatinumMaster/NitroSharp
          path: NitroSharp
      - run: dotnet build SwissArmyKnife --configuration Release
      - run: dotnet publish -c Release SwissArmyKnife
      - name: Upload build artifacts (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: SAK-${{ matrix.os }}-${{ github.sha }}
          path: ${{github.workspace}}\SwissArmyKnife\bin\Release\net6.0\publish\ 
      - name: Upload build artifacts (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: SAK-${{ matrix.os}}-${{ github.sha }}
          path:  ${{github.workspace}}/SwissArmyKnife/bin/Release/net6.0/publish
      - name: Upload build artifacts (MacOS)
        if: ${{ matrix.os == 'macos-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: SAK-${{ matrix.os}}-${{ github.sha }}
          path: ${{github.workspace}}/SwissArmyKnife/bin/Release/net6.0/publish/      
      - uses: actions/download-artifact@v3
        with:
          name: SAK-${{ matrix.os}}-${{ github.sha }}
          path: ${{github.workspace}}/SAK-${{ matrix.os}}-${{ github.sha }}
      - name: Archive artifacts
        uses: thedoctor0/zip-release@0.7.1
        with:
          path: SAK-${{ matrix.os}}-${{ github.sha }}
          type: 'zip'
          filename: SAK-${{matrix.os}}-${{ env.TAG }}.zip
      - name: Make release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: ${{ env.TAG }}
          commit: ${{ github.sha }}
          name: Release ${{ github.sha }}
          artifacts: SAK-${{matrix.os}}-${{ env.TAG }}.zip
