name: SwissArmyKnife.Avalonia

on:
  push:
    branches: [ avalonia ]
  pull_request:
    branches: [ avalonia ]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.config.os }}
        
    env:
      working-directory: SwissArmyKnife
    steps:
    - name: Checkout SwissArmyKnife.Avalonia
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: SwissArmyKnife
    - name: Checkout BeaterLibrary
      uses: actions/checkout@v2
      with:
        repository: PlatinumMaster/BeaterLibrary
        path: BeaterLibrary

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
          
    # Build project
    - name: Install dependencies
      run: dotnet restore SwissArmyKnife
      
    - name: Build
      run: dotnet build SwissArmyKnife --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release SwissArmyKnife
              
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: SwissArmyKnife.Avalonia-${{ matrix.config.os }}-${{ github.sha }}
        path: SwissArmyKnife/SwissArmyKnife/bin/${{ matrix.configuration }}/net5.0\publish/
